### ISSUE TITLE
Bug when the excerpt image is deleted

### ISSUE THREAD

**Issue by benbet** [EtonDigital/EDBlogBundle#20]
Hello,

Thank's for your job ! It's a pleasure to use it ;-)

But I found a bug when I want to delete the excerpt image from my article ... the image is not deleted ???

Is it possible to correct this bug ?

Regards
Ben

**Comment by vmladenovic** [comment]
Hello benbet,

Thank you for using EDBlogBundle and for noticing this issue. It is fixed in version v1.0.5

Vladimir
