### ISSUE TITLE
Admin area credentials for demo

### ISSUE THREAD

**Issue by zoka123** [EtonDigital/EDBlogBundle#22]
Hi,

I've tried to log in http://blog-demo.etonlabs.com/ admin area but I can't find admin credentials?

Am I missing something or they aren't provided.

Great job, I need to check it out and I believe we'll
adopt it as solution and contribute to further development.

**Comment by vmladenovic** [comment]
Hi zoka123,

To be able to access admin area you should be registered as admin on following link:

http://blog-demo.etonlabs.com/register/admin

Thank you for using EDBlogBundle

Vladimir
