### ISSUE TITLE
using with jms/serialize 1.1

### ISSUE THREAD

**Issue by ciro-webcom** [EtonDigital/EDBlogBundle#30]
Hi,

Is it possible tu use the bundle with symfony 3.1 and jms/serialize 1.1? I'm on symfony 3.1, and I can't use jms/serialize 0.13.0 as mentioned in your cinfig.json.

Thank you

**Comment by milos-ilic** [comment]
Hi @ciro-webcom 

You can try with [dev-symfony3 branch](https://github.com/EtonDigital/EDBlogBundle/tree/dev-symfony3) we are still testing it but it is used in some projects without problems

**Comment by ciro-webcom** [comment]
Thank you!!
